"""
Transaction definitions for InferenceChain.

Three families:
  SIMPLE    — user-initiated (transfers, staking, contracts)
  INFERENCE — one per block, triggers QoI consensus round
  SYSTEM    — generated by the protocol (responses, results, rewards, slashes)
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from .utils import sha256_json, now


# ── Enums ─────────────────────────────────────────────────────────────────────

class TxFamily(str, Enum):
    SIMPLE    = "simple"
    INFERENCE = "inference"
    SYSTEM    = "system"


class TxType(str, Enum):
    # ── Simple ────────────────────────────────────────────────────────────────
    TOKEN_TRANSFER      = "token_transfer"
    STAKE               = "stake"
    UNSTAKE             = "unstake"
    NODE_REGISTER       = "node_register"       # legacy / genesis only
    NODE_REGISTER_DNN   = "node_register_dnn"   # DNN validator registration
    NODE_REGISTER_POS   = "node_register_pos"   # PoS-only validator registration
    MODEL_RESPONSE      = "model_response"      # node answers PoM challenge
    CONTRACT_DEPLOY     = "contract_deploy"
    CONTRACT_CALL       = "contract_call"
    # ── Inference ─────────────────────────────────────────────────────────────
    INFERENCE_REQUEST   = "inference_request"
    # ── System ────────────────────────────────────────────────────────────────
    INFERENCE_RESPONSE  = "inference_response"
    CONSENSUS_RESULT    = "consensus_result"
    REWARD              = "reward"
    SLASH               = "slash"
    MODEL_CHALLENGE     = "model_challenge"     # protocol issues PoM challenge
    MODEL_VERIFY        = "model_verify"        # validator submits verification
    NODE_ADMITTED       = "node_admitted"       # node passed PoM
    NODE_REJECTED       = "node_rejected"       # node failed PoM


_TX_FAMILY: dict[TxType, TxFamily] = {
    TxType.TOKEN_TRANSFER:    TxFamily.SIMPLE,
    TxType.STAKE:             TxFamily.SIMPLE,
    TxType.UNSTAKE:           TxFamily.SIMPLE,
    TxType.NODE_REGISTER:     TxFamily.SIMPLE,
    TxType.NODE_REGISTER_DNN: TxFamily.SIMPLE,
    TxType.NODE_REGISTER_POS: TxFamily.SIMPLE,
    TxType.MODEL_RESPONSE:    TxFamily.SIMPLE,
    TxType.CONTRACT_DEPLOY:   TxFamily.SIMPLE,
    TxType.CONTRACT_CALL:     TxFamily.SIMPLE,
    TxType.INFERENCE_REQUEST: TxFamily.INFERENCE,
    TxType.INFERENCE_RESPONSE:TxFamily.SYSTEM,
    TxType.CONSENSUS_RESULT:  TxFamily.SYSTEM,
    TxType.REWARD:            TxFamily.SYSTEM,
    TxType.SLASH:             TxFamily.SYSTEM,
    TxType.MODEL_CHALLENGE:   TxFamily.SYSTEM,
    TxType.MODEL_VERIFY:      TxFamily.SYSTEM,
    TxType.NODE_ADMITTED:     TxFamily.SYSTEM,
    TxType.NODE_REJECTED:     TxFamily.SYSTEM,
}


# ── Payload dataclasses ───────────────────────────────────────────────────────

@dataclass
class TokenTransferPayload:
    amount: float

    def to_dict(self) -> dict:
        return {"amount": self.amount}


@dataclass
class StakePayload:
    amount: float

    def to_dict(self) -> dict:
        return {"amount": self.amount}


@dataclass
class UnstakePayload:
    amount: float

    def to_dict(self) -> dict:
        return {"amount": self.amount}


@dataclass
class NodeRegisterPayload:
    model_name:  str
    public_key:  str    # hex-encoded public key
    endpoint:    str    # host:port of the node's API

    def to_dict(self) -> dict:
        return {
            "model_name": self.model_name,
            "public_key": self.public_key,
            "endpoint":   self.endpoint,
        }


@dataclass
class ContractDeployPayload:
    bytecode:         str        # serialised SimpleVM bytecode
    abi:              dict       # function signatures
    constructor_args: list[Any]

    def to_dict(self) -> dict:
        return {
            "bytecode":         self.bytecode,
            "abi":              self.abi,
            "constructor_args": self.constructor_args,
        }


@dataclass
class ContractCallPayload:
    contract_address: str
    function:         str
    args:             list[Any]
    value:            float = 0.0    # INFER sent with the call

    def to_dict(self) -> dict:
        return {
            "contract_address": self.contract_address,
            "function":         self.function,
            "args":             self.args,
            "value":            self.value,
        }


@dataclass
class InferenceRequestPayload:
    request_id:  str    # unique ID for this inference job
    image_hash:  str    # SHA-256 of the raw image bytes
    model_hint:  str    # preferred model name (or "any")

    def to_dict(self) -> dict:
        return {
            "request_id": self.request_id,
            "image_hash": self.image_hash,
            "model_hint": self.model_hint,
        }


@dataclass
class InferenceResponsePayload:
    request_id:      str
    node_id:         str
    probabilities:   list[float]   # softmax output, length = NUM_CLASSES
    predicted_class: int

    def to_dict(self) -> dict:
        return {
            "request_id":      self.request_id,
            "node_id":         self.node_id,
            "probabilities":   self.probabilities,
            "predicted_class": self.predicted_class,
        }


@dataclass
class ConsensusResultPayload:
    request_id:          str
    final_class:         int
    confidence:          float
    participating_nodes: list[str]   # node_ids that contributed

    def to_dict(self) -> dict:
        return {
            "request_id":          self.request_id,
            "final_class":         self.final_class,
            "confidence":          self.confidence,
            "participating_nodes": self.participating_nodes,
        }


@dataclass
class RewardPayload:
    amount:     float
    reason:     str
    request_id: str

    def to_dict(self) -> dict:
        return {
            "amount":     self.amount,
            "reason":     self.reason,
            "request_id": self.request_id,
        }


@dataclass
class SlashPayload:
    amount:     float
    reason:     str
    request_id: str

    def to_dict(self) -> dict:
        return {
            "amount":     self.amount,
            "reason":     self.reason,
            "request_id": self.request_id,
        }


@dataclass
class NodeRegisterDNNPayload:
    """DNN validator registration with model commitment."""
    model_name:    str          # e.g. "resnet20"
    architecture:  dict         # JSON layer spec {layers, input_size, num_classes}
    weights_hash:  str          # SHA-256(weights_file) — on-chain commitment
    endpoint:      str          # host:port serving /weights and /predict
    dataset_id:    str          # "cifar10" | "imagenet_subset"
    public_key:    str          # hex-encoded public key

    def to_dict(self) -> dict:
        return {
            "model_name":   self.model_name,
            "architecture": self.architecture,
            "weights_hash": self.weights_hash,
            "endpoint":     self.endpoint,
            "dataset_id":   self.dataset_id,
            "public_key":   self.public_key,
        }


@dataclass
class NodeRegisterPOSPayload:
    """PoS-only validator registration — no model required."""
    endpoint:   str
    public_key: str

    def to_dict(self) -> dict:
        return {
            "endpoint":   self.endpoint,
            "public_key": self.public_key,
        }


@dataclass
class ModelChallengePayload:
    """Protocol-issued PoM challenge (system tx)."""
    node_id:           str
    challenge_indices: list[int]   # 50 deterministic CIFAR-10 test indices
    ground_truth:      list[int]   # correct labels at those indices
    dataset_id:        str

    def to_dict(self) -> dict:
        return {
            "node_id":           self.node_id,
            "challenge_indices": self.challenge_indices,
            "ground_truth":      self.ground_truth,
            "dataset_id":        self.dataset_id,
        }


@dataclass
class ModelResponsePayload:
    """Node's answer to the PoM challenge (simple tx)."""
    node_id:     str
    predictions: list[int]   # argmax for each challenge sample (same order)

    def to_dict(self) -> dict:
        return {
            "node_id":     self.node_id,
            "predictions": self.predictions,
        }


@dataclass
class ModelVerifyPayload:
    """Validator's independent verification result (system tx)."""
    node_id:       str
    verified:      bool
    accuracy:      float
    weights_match: bool    # SHA-256(downloaded_weights) == weights_hash on-chain

    def to_dict(self) -> dict:
        return {
            "node_id":       self.node_id,
            "verified":      self.verified,
            "accuracy":      self.accuracy,
            "weights_match": self.weights_match,
        }


@dataclass
class NodeAdmittedPayload:
    """Protocol emits this when 2f+1 positive verifications received."""
    node_id:      str
    node_type:    str    # "dnn" | "pos"
    final_accuracy: float

    def to_dict(self) -> dict:
        return {
            "node_id":        self.node_id,
            "node_type":      self.node_type,
            "final_accuracy": self.final_accuracy,
        }


@dataclass
class NodeRejectedPayload:
    """Protocol emits this when PoM fails."""
    node_id: str
    reason:  str

    def to_dict(self) -> dict:
        return {
            "node_id": self.node_id,
            "reason":  self.reason,
        }


# ── Transaction ───────────────────────────────────────────────────────────────

@dataclass
class Transaction:
    tx_type:   TxType
    sender:    str                  # 40-char hex address
    payload:   Any                  # one of the payload dataclasses above
    nonce:     int                  # per-sender monotonic counter
    fee:       float       = 0.0    # INFER fee (0 for SYSTEM txs)
    recipient: Optional[str] = None
    timestamp: float       = field(default_factory=now)
    signature: Optional[str] = None

    # Computed after init
    tx_id: str = field(init=False)

    def __post_init__(self) -> None:
        self.tx_id = self._compute_id()

    # ── Identity ──────────────────────────────────────────────────────────────

    def _compute_id(self) -> str:
        data = {
            "tx_type":   self.tx_type.value,
            "sender":    self.sender,
            "recipient": self.recipient,
            "payload":   self.payload.to_dict(),
            "nonce":     self.nonce,
            "fee":       self.fee,
            "timestamp": self.timestamp,
        }
        return sha256_json(data)

    @property
    def family(self) -> TxFamily:
        return _TX_FAMILY[self.tx_type]

    # ── Serialisation ─────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "tx_id":     self.tx_id,
            "tx_type":   self.tx_type.value,
            "family":    self.family.value,
            "sender":    self.sender,
            "recipient": self.recipient,
            "payload":   self.payload.to_dict(),
            "nonce":     self.nonce,
            "fee":       self.fee,
            "timestamp": self.timestamp,
            "signature": self.signature,
        }

    @classmethod
    def from_dict(cls, d: dict) -> Transaction:
        tx_type = TxType(d["tx_type"])
        payload = _payload_from_dict(tx_type, d["payload"])
        tx = cls(
            tx_type   = tx_type,
            sender    = d["sender"],
            payload   = payload,
            nonce     = d["nonce"],
            fee       = d.get("fee", 0.0),
            recipient = d.get("recipient"),
            timestamp = d["timestamp"],
            signature = d.get("signature"),
        )
        # Preserve original tx_id (don't recompute from potentially different timestamp)
        tx.tx_id = d["tx_id"]
        return tx

    def __repr__(self) -> str:
        return f"Transaction({self.tx_type.value}, id={self.tx_id[:8]}..., sender={self.sender[:8]}...)"


# ── Payload deserialisation ───────────────────────────────────────────────────

def _payload_from_dict(tx_type: TxType, d: dict) -> Any:
    match tx_type:
        case TxType.TOKEN_TRANSFER:
            return TokenTransferPayload(amount=d["amount"])
        case TxType.STAKE:
            return StakePayload(amount=d["amount"])
        case TxType.UNSTAKE:
            return UnstakePayload(amount=d["amount"])
        case TxType.NODE_REGISTER:
            return NodeRegisterPayload(
                model_name=d["model_name"],
                public_key=d["public_key"],
                endpoint=d["endpoint"],
            )
        case TxType.NODE_REGISTER_DNN:
            return NodeRegisterDNNPayload(
                model_name=d["model_name"],
                architecture=d["architecture"],
                weights_hash=d["weights_hash"],
                endpoint=d["endpoint"],
                dataset_id=d["dataset_id"],
                public_key=d["public_key"],
            )
        case TxType.NODE_REGISTER_POS:
            return NodeRegisterPOSPayload(
                endpoint=d["endpoint"],
                public_key=d["public_key"],
            )
        case TxType.MODEL_CHALLENGE:
            return ModelChallengePayload(
                node_id=d["node_id"],
                challenge_indices=d["challenge_indices"],
                ground_truth=d["ground_truth"],
                dataset_id=d["dataset_id"],
            )
        case TxType.MODEL_RESPONSE:
            return ModelResponsePayload(
                node_id=d["node_id"],
                predictions=d["predictions"],
            )
        case TxType.MODEL_VERIFY:
            return ModelVerifyPayload(
                node_id=d["node_id"],
                verified=d["verified"],
                accuracy=d["accuracy"],
                weights_match=d["weights_match"],
            )
        case TxType.NODE_ADMITTED:
            return NodeAdmittedPayload(
                node_id=d["node_id"],
                node_type=d["node_type"],
                final_accuracy=d["final_accuracy"],
            )
        case TxType.NODE_REJECTED:
            return NodeRejectedPayload(
                node_id=d["node_id"],
                reason=d["reason"],
            )
        case TxType.CONTRACT_DEPLOY:
            return ContractDeployPayload(
                bytecode=d["bytecode"],
                abi=d["abi"],
                constructor_args=d["constructor_args"],
            )
        case TxType.CONTRACT_CALL:
            return ContractCallPayload(
                contract_address=d["contract_address"],
                function=d["function"],
                args=d["args"],
                value=d.get("value", 0.0),
            )
        case TxType.INFERENCE_REQUEST:
            return InferenceRequestPayload(
                request_id=d["request_id"],
                image_hash=d["image_hash"],
                model_hint=d["model_hint"],
            )
        case TxType.INFERENCE_RESPONSE:
            return InferenceResponsePayload(
                request_id=d["request_id"],
                node_id=d["node_id"],
                probabilities=d["probabilities"],
                predicted_class=d["predicted_class"],
            )
        case TxType.CONSENSUS_RESULT:
            return ConsensusResultPayload(
                request_id=d["request_id"],
                final_class=d["final_class"],
                confidence=d["confidence"],
                participating_nodes=d["participating_nodes"],
            )
        case TxType.REWARD:
            return RewardPayload(
                amount=d["amount"],
                reason=d["reason"],
                request_id=d["request_id"],
            )
        case TxType.SLASH:
            return SlashPayload(
                amount=d["amount"],
                reason=d["reason"],
                request_id=d["request_id"],
            )
        case _:
            raise ValueError(f"Unknown tx_type: {tx_type}")
